# Generated by Django 3.2.5 on 2021-07-25 01:45

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
                ('custom_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
