# Generated by Django 3.2.5 on 2021-07-29 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormaDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplicador', models.SmallIntegerField(choices=[(1, 'Positivo'), (-1, 'Negativo')], default=1)),
                ('valor', models.FloatField()),
            ],
            options={
                'unique_together': {('multiplicador', 'valor')},
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('precio', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='commerce.cotizacion')),
                ('creado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to=settings.AUTH_USER_MODEL)),
                ('forma_de_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='commerce.formadepago')),
                ('para', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_recibidas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductoCotizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.FloatField()),
                ('cantidad', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(max_length=255)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='commerce.cotizacion')),
            ],
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='formas_de_pago',
            field=models.ManyToManyField(related_name='cotizaciones', to='commerce.FormaDePago'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='para',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones_recibidas', to=settings.AUTH_USER_MODEL),
        ),
    ]
